import type { StaticImport } from 'next/dist/shared/lib/get-img-props'
import scen1ItemImage1 from './scen1/item1.svg'
import scen1ItemImage2 from './scen1/item2.svg'
import scen1ItemImage3 from './scen1/item3.svg'
import scen1MainImage from './scen1/main.svg'

import scen2ItemImage1 from './scen2/item1.svg'
import scen2ItemImage2 from './scen2/item2.svg'
import scen2ItemImage3 from './scen2/item3.svg'

import scen3ItemImage1 from './scen3/item1.svg'
import scen3ItemImage2 from './scen3/item2.svg'
import scen3ItemImage3 from './scen3/item3.svg'

import scen4ItemImage1 from './scen4/item1.svg'
import scen4ItemImage2 from './scen4/item2.svg'
import scen4ItemImage3 from './scen4/item3.svg'
import scen4ItemImage4 from './scen4/item4.svg'
import scen4ItemImage5 from './scen4/item5.svg'

import scen5ItemImage1 from './scen5/item1.svg'
import scen5ItemImage2 from './scen5/item2.svg'
import scen5ItemImage3 from './scen5/item3.svg'
import scen5ItemImage4 from './scen5/item4.svg'

export type IScenDataImage = string | StaticImport

export type IScenDataImageTextList = Array<{
  image: IScenDataImage
  text: string[]
  textIsListStyle?: boolean
}>

export interface IScenDataItem {
  scen: string
  title: string
  description: string
  mainImage: IScenDataImage
  imageTextList: IScenDataImageTextList
}

const scenDataList: IScenDataItem[] = [
  {
    scen: 'scen1',
    title: 'Empower office automation',
    description: 'Empower enterprises to create and distribute spreadsheets, doc, and slides to their employees, fulfilling the requirements for automating the delivery of reports, contracts, approval forms, official documents, and other business reports. Optimize workflow management and enhance team collaboration.',
    mainImage: scen1MainImage,
    imageTextList: [
      {
        image: scen1ItemImage1,
        text: [
          'Empower enterprises to create and distribute spreadsheets, doc, and slides to their employees, fulfilling the requirements for automating the delivery of reports, contracts, approval forms, official documents, and other business reports. Optimize workflow management and enhance team collaboration.',
          'Univer is an isomorphic full-stack framework that allows developers to easily create content-rich snapshots of spreadsheets, documents, and slides on the server side using the Univer API. A snapshot is a JSON data structure defined by Univer, which can include business data, formulas, charts, images, shapes, pivot tables, conditional formatting, and any other configuration data.',
        ],
      },
      {
        image: scen1ItemImage2,
        text: [
          'To enable employees to directly view and edit these snapshots within the enterprise system, you can embed the Univer SDK into the system. This will allow employees to preview and edit spreadsheets, docs, and slides online, they can even collaborate and share them via a URL link.',
          'If you prefer not to expose data generated by formulas, pivot tables, and other features to all employees, you can leverage Univer\'s server-side computing capabilities to pre-calculate formulas and pivot tables. You can then push only the snapshot of the final results, further enhancing enterprise workflow management and improving collaboration efficiency.',
        ],
      },
      {
        image: scen1ItemImage3,
        text: [
          'Univer adopts a modular plugin architecture, where each plugin corresponds to a specific feature. Currently, Univer offers over 100 plugins. Enterprise developers can extend existing functionalities, such as adding new data validation types, customizing permission rules, creating new formulas, and adding data aggregation logic for pivot tables. Additionally, enterprise developers can easily create their own plugins to meet the unique business needs of the company.',
        ],
      },
    ],
  },
  {
    scen: 'scen2',
    title: 'Revamp data submission and collection',
    description: 'Provide enterprise-level complex data template design, utilizing spreadsheets to meet the needs of bulk data collection and submission. Easily gather data, quickly consolidate it, and significantly boost efficiency.',
    mainImage: scen1MainImage,
    imageTextList: [
      {
        image: scen2ItemImage1,
        text: [
          'Since Univer is an isomorphic full-stack framework, it allows developers to create various complex spreadsheet snapshots on the server side. A snapshot is a JSON data structure defined by Univer, supporting features such as cell text styles, cell background styles, merged cells, frozen rows and columns, hidden rows and columns, row heights and column widths, formulas, and data validation. All of these are accomplished using the Univer API, making it easy for any developer to get started quickly.',
        ],
      },
      {
        image: scen2ItemImage2,
        text: [
          'Developers can then embed the Univer SDK into their enterprise systems, allowing employees to directly open these snapshots within the system, enabling online viewing and editing of spreadsheets, documents, and slides. The Univer SDK offers an Office-like experience, supporting convenient operations such as selection statistics, copy-paste, undo-redo, drag-fill, inserting and deleting rows and columns, freezing rows and columns, and more. This enables employees to get started quickly without any training.',
          'At the same time, developers can write data from the database into the snapshots and set viewing or editing permissions for the cells, worksheets, or workbooks containing that data, ensuring comprehensive data security.',
        ],
      },
      {
        image: scen2ItemImage3,
        text: [
          'To ensure that employees follow standardized data entry practices, developers can pre-configure data constraint rules for cells using Univer\'s data validation feature. Based on Univer\'s modular plugin architecture, where each plugin corresponds to a specific function (with over 100 plugins currently available), developers can modify the data constraint rules of the data validation plugin to meet various types of data verification tasks.',
          'At this point, the data collection template pushed by the enterprise is a Univer snapshot generated on the server. This snapshot acts as a data template, containing permissions, data constraint rules, formulas, and complex styles. Employees can then complete data entry tasks based on this template. The data entry process is highly convenient, with options such as directly inputting content into cells, using drag-fill, bulk pasting, or importing Excel templates, greatly enhancing the efficiency of data submission and collection for the enterprise.',
        ],
      },
    ],
  },
  {
    scen: 'scen3',
    title: 'Propel online data analysis',
    description: 'Meet the enterprise\'s need for automating the creation of complex reports, charts, dashboards, and business reports, accelerating data processing and enabling rapid decision-making.',
    mainImage: scen1MainImage,
    imageTextList: [
      {
        image: scen3ItemImage1,
        text: [
          'Univer is an isomorphic full-stack framework that allows enterprise developers to generate snapshots of spreadsheets, docs, and slides in any format using the Univer API on the server side. A snapshot is a JSON data structure defined by Univer, which enables the creation of complex reports by incorporating text color, background color, rich text, merged cells, and more than 500 formulas. Additionally, with Univer’s built-in features like charts, sparklines, and conditional formatting, you can easily create interactive and editable dashboards and business analysis reports.',
        ],
      },
      {
        image: scen3ItemImage2,
        text: [
          'Univer Spreadsheet provides the same user experience as Excel, allowing business experts to create report templates using over 500 formulas. Developers can then seamlessly integrate data from the BI system into the templates, automatically generating reports and delivering them to enterprise managers for review. In this process, developers don’t need to worry about the details of the formulas in the report templates, and business experts don’t need to handle data connections from the BI system, enabling more efficient collaboration and accelerating the process in data analysis.',
        ],
      },
      {
        image: scen3ItemImage3,
        text: [
          'Univer adopts a modular plugin architecture, with each plugin corresponding to a specific feature. Currently, Univer has over 100 plugins. Developers can extend the chart plugin to support more specialized chart types to assist business experts. Similar extensions are also applicable to plugins for sparklines, conditional formatting, dashboards, formulas, and slicers. Developers can also add more plugins to meet the customized functional needs of the enterprise.',
          'Developers can embed Univer Spreadsheets into their enterprise systems, enabling the use of powerful analysis features such as sparklines, conditional formatting, pivot tables, and charts for direct data analysis within the system.',
        ],
      },
    ],
  },
  {
    scen: 'scen4',
    title: 'Build your own Wiki',
    description: 'Meet the enterprise\'s need for building a Wiki on a private cloud, enabling the capability to accumulate and share internal knowledge while ensuring data security.',
    mainImage: scen1MainImage,
    imageTextList: [
      {
        image: scen4ItemImage1,
        text: [
          'Knowledge within an enterprise is often scattered across various departments and employees, making it difficult to manage systematically. New employees may find it hard to quickly access the information they need, and the departure of employees can lead to the loss of critical knowledge, affecting business continuity. Building a Wiki on a private cloud not only solves the issue of knowledge retention but also enables quick adaptation to business changes. More importantly, deploying the Wiki within the enterprise\'s internal network ensures data security, controls access permission, and prevents the leakage of confidential information.',
        ],
      },
      {
        image: scen4ItemImage2,
        text: [
          'Univer is an isomorphic full-stack framework that helps enterprises build a powerful Wiki on a private cloud, covering productivity tools such as spreadsheets, docs, and slides. Its key features are as follows:',
          'Univer Spreadsheet offers an Excel-like user experience, supporting convenient operations such as selection statistics, copy-paste, undo-redo, drag-fill, inserting/deleting rows and columns, and freezing. It also includes advanced features such as pivot tables, data validation, conditional formatting, sparklines, charts, images, and comments.',
          '○Univer Doc provides a Word-like user experience, supporting paragraph editing, ordered and unordered lists, tables, page breaks, headers and footers, comments, and other features. ',
          '○Univer Slide offers a PowerPoint-like user experience, supporting slide management, master slides, images, charts, shapes, comments, and other features.',
        ],
        textIsListStyle: true,
      },
      {
        image: scen4ItemImage3,
        text: [
          'Univer uses a modular plugin architecture, with each plugin corresponding to a specific feature. Currently, Univer has over 100 plugins. Developers can extend any plugin to meet the customized needs of an enterprise Wiki, such as custom formulas, specialized chart types, personalized UI, and company logos.',
        ],
      },
      {
        image: scen4ItemImage4,
        text: [
          'As an isomorphic full-stack framework, Univer can integrate with an enterprise\'s permission system to precisely control data sharing, copy-paste functionality, and watermarking. For example, in spreadsheets, enterprises can precisely manage viewing and editing permissions at the cell, worksheet, and workbook levels, meeting strict data security requirements.',
        ],
      },
      {
        image: scen4ItemImage5,
        text: [
          'Univer supports collaborative editing and version history features, utilizing OT (Operational Transformation) algorithms to resolve conflicts during multi-user editing. It allows up to 200 people to edit a document simultaneously and up to 1,000 people to view a document at the same time, adhering to industry best standards. The version history feature enables employees to track editing changes and restore document data to any previous point, ensuring a reliable and secure user experience.',
        ],
      },
    ],
  },
  {
    scen: 'scen5',
    title: 'Break down data silos',
    description: 'Univer is an isomorphic full-stack framework, which enables Univer\'s spreadsheets, docs, and slides to be viewed and edited as synchronized blocks across different enterprise systems. Employees can insert, copy-paste, share, edit, and view these synchronized blocks, meeting the needs of enterprises for multi-user collaboration and knowledge sharing. This helps break down information silos between systems and unlock the potential value of enterprise data.',
    mainImage: scen1MainImage,
    imageTextList: [
      {
        image: scen5ItemImage1,
        text: [
          'Univer is an isomorphic full-stack framework, which enables Univer\'s spreadsheets, docs, and slides to be viewed and edited as synchronized blocks across different enterprise systems. Employees can insert, copy-paste, share, edit, and view these synchronized blocks, meeting the needs of enterprises for multi-user collaboration and knowledge sharing. This helps break down information silos between systems and unlock the potential value of enterprise data.',
        ],
      },
      {
        image: scen5ItemImage2,
        text: [
          'Enterprises can embed the Univer SDK into any system, such as Wiki, IM, Email, ERP, or CRM. Through Univer\'s web interface, employees can edit spreadsheets, docs, and slides directly in the browser. The user experience is similar to Office, allowing employees to get started quickly without any training.',
        ],
      },
      {
        image: scen5ItemImage3,
        text: [
          'With Univer\'s collaboration features, enterprise employees can conduct multi-user collaborative editing within synchronized blocks. Even though these blocks are distributed across different systems within the enterprise, cross-application collaboration is achieved, ultimately reshaping the company\'s workflow.',
        ],
      },
      {
        image: scen5ItemImage4,
        text: [
          'Univer uses a modular plugin architecture, with each plugin corresponding to a specific feature. Currently, Univer has over 100 plugins. Developers can extend any plugin to enhance the functionality of synchronized blocks, helping enterprises create custom cross-application synchronized blocks to meet personalized needs.',
        ],
      },
    ],
  },
  {
    scen: 'scen6',
    title: 'Revolutionize enterprise applications',
    description: 'Univer adopts a modular plugin architecture, with each plugin corresponding to a specific function. Currently, Univer has over 100 plugins. Developers can extend any plugin to enrich existing functionalities.',
    mainImage: scen1MainImage,
    imageTextList: [

    ],
  },
]

export default scenDataList
