import Container from '@/components/container'
import Title from '@/components/title'
import Image from 'next/image'
import itemImage1 from './item1.svg'
import itemImage2 from './item2.svg'
import itemImage3 from './item3.svg'

export default function List() {
  return (
    <section className={`
      relative mb-24

      xl:mb-48
    `}
    >
      <Container>
        <Title level="h1" align="center" className="mb-20">
          Enable office automation
        </Title>

        <ul className="relative mx-auto grid max-w-[1000px] grid-cols-1 divide-y divide-white/15 text-sm text-white/50">
          {/* spotlight */}
          <div className={`
            absolute left-0 top-[50%] z-[-1] h-[970px] w-[660px] shrink-0 translate-y-[-50%] rounded-[970px]
            blur-[200px]

            [background:linear-gradient(90deg,rgba(0,94,181,0.52)_0%,rgba(114,0,166,0.52)_104.41%)]
          `}
          >
          </div>

          <li className="flex items-start pb-[120px]">
            <Image
              src={itemImage1}
              width="400"
              alt=""
            />
            <div className="ml-14 flex min-h-[230px] flex-col justify-center">
              <p>Empower enterprises to create and distribute spreadsheets, doc, and slides to their employees, fulfilling the requirements for automating the delivery of reports, contracts, approval forms, official documents, and other business reports. Optimize workflow management and enhance team collaboration.</p>
              <p className="mt-4">Univer is an isomorphic full-stack framework that allows developers to easily create content-rich snapshots of spreadsheets, documents, and slides on the server side using the Univer API. A snapshot is a JSON data structure defined by Univer, which can include business data, formulas, charts, images, shapes, pivot tables, conditional formatting, and any other configuration data.</p>
            </div>
          </li>
          <li className="flex items-start py-[120px]">
            <div className="mr-14 flex min-h-[230px] flex-col justify-center">
              <p>To enable employees to directly view and edit these snapshots within the enterprise system, you can embed the Univer SDK into the system. This will allow employees to preview and edit spreadsheets, docs, and slides online, they can even collaborate and share them via a URL link.</p>
              <p className="mt-4">If you prefer not to expose data generated by formulas, pivot tables, and other features to all employees, you can leverage Univer's server-side computing capabilities to pre-calculate formulas and pivot tables. You can then push only the snapshot of the final results, further enhancing enterprise workflow management and improving collaboration efficiency.</p>
            </div>
            <Image
              src={itemImage2}
              width="400"
              alt=""
            />
          </li>
          <li className="flex items-start pt-[120px]">
            <Image
              src={itemImage3}
              width="400"
              alt=""
            />
            <div className="ml-14 flex min-h-[230px] flex-col justify-center">
              <p>Univer adopts a modular plugin architecture, where each plugin corresponds to a specific feature. Currently, Univer offers over 100 plugins. Enterprise developers can extend existing functionalities, such as adding new data validation types, customizing permission rules, creating new formulas, and adding data aggregation logic for pivot tables. Additionally, enterprise developers can easily create their own plugins to meet the unique business needs of the company.</p>
            </div>
          </li>
        </ul>
      </Container>
    </section>
  )
}
